[ADVICE]
long=-4
short=2
stoploss=2
flexibility=0
exposed=false
[Ticker]
_tickerSize=60
SMA=1
MACD=1
[MainIndicators]
SMA=1
EMA=0
DEMA=0
AROON=1
AROONOSC=1
BOP=1
CCI=1
CMO=1
MACD=1
PPO=1
RSI=1
STOCH=1
HT_PHASOR=1
HT_TRENDMODE=1
CDLHARAMICROSS=1
CANDLE=1
[SMA]
optInTimePeriod=50
log=true
use_1=1
ConditionVector_1=1
ConditionWeight_1=2
ConditionLimit_1=0.2
ConditionPersistence_1=0
use_3=1
ConditionVector_3=-1
ConditionWeight_3=10
ConditionLimit_3=0.2
ConditionPersistence_3=0
[TickerMACD]
log=true
optInFastPeriod=10
optInSlowPeriod=21
optInSignalPeriod=9
use_1=1
ConditionVector_1=-1
ConditionWeight_1=1.1
ConditionLimit_1=-13
ConditionPersistence_1=0
[TickerSMA]
optInTimePeriod=3
log=true
use_1=0
ConditionVector_1=-1
ConditionWeight_1=1
ConditionLimit_1=0
ConditionPersistence_1=0
use_2=0
ConditionVector_2=1
ConditionWeight_2=1
ConditionLimit_2=0
ConditionPersistence_2=0
use_3=0
ConditionVector_3=-1
ConditionWeight_3=0.9
ConditionLimit_3=0
ConditionPersistence_3=0
use_4=0
ConditionVector_4=1
ConditionWeight_4=1
ConditionLimit_4=0
ConditionPersistence_4=0
[FileLog]
fileLog=true
logCandles=true
logNotImportantCandle=true
logFilePath="logFilePath.txt"
candleHeder="#"
candleFooter="*"
forLength=50
seperator="@"
[CDLHARAMICROSS]
log=true
use_1=0
ConditionVector_1=1
ConditionWeight_1=0.1
ConditionLimit_1=0
ConditionPersistence_1=0
use_2=0
ConditionVector_2=1
ConditionWeight_2=0.1
ConditionLimit_2=0
ConditionPersistence_2=0
[MACD]
log=true
optInFastPeriod=10
optInSlowPeriod=21
optInSignalPeriod=9
use_1=0
ConditionVector_1=-1
ConditionWeight_1=1
ConditionLimit_1=60
ConditionPersistence_1=0
use_2=0
ConditionVector_2=1
ConditionWeight_2=1
ConditionLimit_2=-55
ConditionPersistence_2=0
use_3=0
ConditionVector_3=-1
ConditionWeight_3=1
ConditionLimit_3=10
ConditionPersistence_3=0
use_4=1
ConditionVector_4=-1
ConditionWeight_4=1.3
ConditionLimit_4=1
ConditionPersistence_4=0
use_5=0
ConditionVector_5=1
ConditionWeight_5=1
ConditionLimit_5=-45
ConditionPersistence_5=0
use_6=0
ConditionVector_6=1
ConditionWeight_6=1
ConditionLimit_6=-17
ConditionPersistence_6=0
use_7=0
ConditionVector_7=1
ConditionWeight_7=1
ConditionLimit_7=-23
ConditionPersistence_7=0
[RSI]
log=true
optInTimePeriod=30
use_1=1
ConditionVector_1=-1
ConditionWeight_1=2.3
ConditionLimit_1=40
ConditionPersistence_1=0.001
use_2=0
ConditionVector_2=1
ConditionWeight_2=1
ConditionLimit_2=85
ConditionPersistence_2=0
use_3=0
ConditionVector_3=1
ConditionWeight_3=30
ConditionLimit_3=22
ConditionPersistence_3=0
[HT_PHASOR]
log=true
use_1=0
ConditionVector_1=1
ConditionWeight_1=3.11
ConditionLimit_1=-50
ConditionPersistence_1=0
use_2=0
ConditionVector_2=-1
ConditionWeight_2=3
ConditionLimit_2=140
ConditionPersistence_2=0
[AROON]
log=true
optInTimePeriod=14
use_1=0
ConditionVector_1=-1
ConditionWeight_1=1
ConditionLimit_1=100
ConditionPersistence_1=0
use_2=1
ConditionVector_2=1
ConditionWeight_2=1
ConditionLimit_2=1
ConditionPersistence_2=0
use_3=0
ConditionVector_3=-1
ConditionWeight_3=1
ConditionLimit_3=0
ConditionPersistence_3=0
[AROONOSC]
log=true
optInTimePeriod=14
use_1=0
ConditionVector_1=-1
ConditionWeight_1=1
ConditionLimit_1=0
ConditionPersistence_1=0
use_2=0
ConditionVector_2=-1
ConditionWeight_2=1
ConditionLimit_2=-1
ConditionPersistence_2=0
use_3=0
ConditionVector_3=-1
ConditionWeight_3=1
ConditionLimit_3=100
ConditionPersistence_3=0
[BOP]
log=true
use_1=0
ConditionVector_1=-1
ConditionWeight_1=1
ConditionLimit_1=0.99
ConditionPersistence_1=0
use_2=0
ConditionVector_2=1
ConditionWeight_2=1
ConditionLimit_2=-0.99
ConditionPersistence_2=0
[CCI]
log=true
optInTimePeriod=14
use_1=0
ConditionVector_1=-1
ConditionWeight_1=1
ConditionLimit_1=200
ConditionPersistence_1=0
use_2=0
ConditionVector_2=1
ConditionWeight_2=1
ConditionLimit_2=-230
ConditionPersistence_2=0
[CMO]
log=true
optInTimePeriod=14
use_1=1
ConditionVector_1=-1
ConditionWeight_1=0
ConditionLimit_1=55
ConditionPersistence_1=0
use_2=0
ConditionVector_2=1
ConditionWeight_2=2
ConditionLimit_2=-69
ConditionPersistence_2=0
[PPO]
log=true
optInFastPeriod=12
optInSlowPeriod=26
optInSignalPeriod=9
optInMAType=1
optInTimePeriod=100
use_1=1
ConditionVector_1=1
ConditionWeight_1=10
ConditionLimit_1=-0.32
ConditionPersistence_1=0
use_2=1
ConditionVector_2=-1
ConditionWeight_2=1
ConditionLimit_2=0.2
ConditionPersistence_2=0.0003
use_3=0
ConditionVector_3=1
ConditionWeight_3=1
ConditionLimit_3=40
ConditionPersistence_3=0
[STOCH]
log=true
optInFastK_Period=1
optInSlowK_Period=3
optInSlowK_MAType=1
optInSlowD_Period=50
optInSlowD_MAType=1
use_1=0
ConditionVector_1=-1
ConditionWeight_1=1
ConditionLimit_1=0
ConditionPersistence_1=0
[CANDLE]
log=true
use_1=1
ConditionVector_1=1
ConditionWeight_1=10
ConditionLimit_1=0.2
ConditionPersistence_1=0
use_2=1
ConditionVector_2=1
ConditionWeight_2=7.5
ConditionLimit_2=90
ConditionPersistence_2=0
use_3=0
ConditionVector_3=1
ConditionWeight_3=1
ConditionLimit_3=90
ConditionPersistence_3=0
use_4=1
ConditionVector_4=-1
ConditionWeight_4=3
ConditionLimit_4=0
ConditionPersistence_4=0
use_5=0
ConditionVector_5=-1
ConditionWeight_5=1
ConditionLimit_5=0
ConditionPersistence_5=0
use_6=1
ConditionVector_6=1
ConditionWeight_6=1.2
ConditionLimit_6=0.11
ConditionPersistence_6=0
use_7=1
ConditionVector_7=1
ConditionWeight_7=0.7
ConditionLimit_7=0.31
ConditionPersistence_7=0
[test]
certainty=-6.7749999999999995
certaintySMA=6.451266666666684